Update config.yaml for chaos-mesh/chaosd
ti-community-infra/configs pull request #578
Opened 2022-05-23 06:39 UTC by WangXiangUSTC

2022-05-23 06:40 UTC, WangXiangUSTC commented
@Mini256 @purelind @cwen0 PTAL

2022-05-23 06:50 UTC, cwen0 approved these changes
LGTM

2022-05-24 02:48 UTC, Mini256 commented
/ok-to-test

2022-05-24 02:58 UTC, Mini256 requested changes

2022-05-24 02:58 UTC, Mini256 commented on prow/config/config.yaml
> +                  - "ci / pull (arm64, integration-test) (pull_request)"
Remove the prefix and suffix of GitHub Action.

```suggestion
                  - "pull (amd64, verify)"
                  - "pull (amd64, build)"
                  - "pull (amd64, unit-test)"
                  - "pull (amd64, integration-test)"
                  - "pull (arm64, verify)"
                  - "pull (arm64, build)"
                  - "pull (arm64, unit-test)"
                  - "pull (arm64, integration-test)"
```

2022-05-24 02:59 UTC, Mini256 approved these changes

2022-05-24 02:59 UTC, Mini256 commented
/merge

2022-05-24 03:00 UTC, merged