prow/config: support tidb feature branch distribute-reorg
ti-community-infra/configs pull request #635
Opened 2022-08-15 06:27 UTC by zimulala

support tidb feature branch: https://github.com/pingcap/tidb/tree/distribute-reorg

2022-08-15 06:31 UTC, zimulala commented
PTAL @purelind

2022-08-16 03:40 UTC, zimulala commented
PTAL @wuhuizuo

2022-08-16 04:07 UTC, wuhuizuo approved these changes

2022-08-16 04:07 UTC, wuhuizuo commented
/ok-to-test

2022-08-16 04:09 UTC, wuhuizuo requested changes

2022-08-16 04:09 UTC, wuhuizuo commented on prow/config/external_plugins_config.yaml
> +          skip_label: skip-issue-check
缩进有问题。

2022-08-16 04:49 UTC, zimulala commented
/retest-required

2022-08-16 05:44 UTC, wuhuizuo approved these changes

2022-08-16 05:44 UTC, wuhuizuo commented
/merge

2022-08-16 05:46 UTC, merged