Add 6.3 to wonfix_versions in tikv repo.
ti-community-infra/configs pull request #681
Opened 2022-10-12 10:24 UTC by MimeLyc

2022-10-12 10:26 UTC, MimeLyc commented
cc @BusyJay

2022-10-12 10:38 UTC, wuhuizuo commented
/ok-to-test

2022-10-12 10:39 UTC, wuhuizuo commented
/cc busyjay

2022-10-12 10:42 UTC, wuhuizuo commented on prow/config/external_plugins_config.yaml
> +      - "3.0"
the item is not in `maintain_versions`, does it need to be contained in the `wontfix_versions` list? @MimeLyc

2022-10-12 10:42 UTC, wuhuizuo commented
rest LGTM

2022-10-13 04:07 UTC, wuhuizuo requested changes

2022-10-13 04:07 UTC, wuhuizuo commented on prow/config/external_plugins_config.yaml
> +    need_cherry_pick_label_prefix: "needs-cherry-pick-"
```suggestion
    need_cherry_pick_label_prefix: "needs-cherry-pick-release-"
```

tikv/tikv is using cherry-pick function in TiChiBot

2022-10-13 04:07 UTC, wuhuizuo commented on prow/config/external_plugins_config.yaml
> -      - pingcap/br
？should delete `tikv/tikv`?

2022-10-13 04:07 UTC, wuhuizuo commented on prow/config/external_plugins_config.yaml
> -      - pingcap/br
@MimeLyc

2022-10-13 04:13 UTC, MimeLyc commented on prow/config/external_plugins_config.yaml
> -      - pingcap/br
my fault. already resolved.

2022-10-14 06:37 UTC, wuhuizuo approved these changes

2022-10-14 06:37 UTC, wuhuizuo commented
/merge

2022-10-14 06:39 UTC, merged